(define tolerance 0.00001)
(define (fixed-point f first-guess)
  (define (close-enough? v1 v2)
    (< (abs (- v1 v2)) tolerance))
  (define (try guess)
    (let ((next (f guess)))
      (print guess)
      (if (close-enough? guess next)
          next
          (try next))))
  (try first-guess))

(define (golden-ratio)
  (fixed-point (lambda (y) (/ (log 1000) (log y)))
               1.01))

(define (golden-ration-average-dumping)
  (fixed-point (lambda (y) (/ (+ (/ (log 1000) (log y)) y) 2 ))
               1.01))
(print (golden-ratio))
(print (golden-ration-average-dumping))
