(define (cont-frac n d k)
  (define (iter i result)
    (cond ((< i 1) result)
          ((= i k) (iter (- i 1) (/ (n k) (d k))))
          (else (iter (- i 1) (/ (n k) (+ (d k) result))))))
  (iter k 0)
  )

(print (+ (cont-frac (lambda (i) 1.0)
                  (lambda (i) (cond ((= i 2) 2)
                                    ((=
                                      (remainder (- i 2) 3) 0)
                                     (+ 2 (/ (* (- i 2) 2) 3)))
                                    (else 1)))
                  100) 2))
