(define (pascal-triangle i j)
  (if (or (= j 1) (= j i))
	  1
	  (+ (pascal-triangle (- i 1) (- j 1)) (pascal-triangle (- i 1) j))
	  ))

(print (pascal-triangle 1 1))
(print (pascal-triangle 2 1))
(print (pascal-triangle 2 2))
(print (pascal-triangle 3 1))
(print (pascal-triangle 3 2))
(print (pascal-triangle 3 3))
(print (pascal-triangle 4 1))
(print (pascal-triangle 4 2))
(print (pascal-triangle 4 3))
(print (pascal-triangle 4 4))
(print (pascal-triangle 5 1))
(print (pascal-triangle 5 2))
(print (pascal-triangle 5 3))
(print (pascal-triangle 5 4))
(print (pascal-triangle 5 5))
