(define (pascal x y)
  (cond ((< x y) -1)
        ((= y 0) 1)
        ((= x y) 1)
        (else (+ (pascal (- x 1) (- y 1)) (pascal (- x 1) y)))
        ))

(print (pascal 0 0))
(print (pascal 1 0))
(print (pascal 1 1))
(print (pascal 2 0))
(print (pascal 2 1))
(print (pascal 2 2))
(print (pascal 3 0))
(print (pascal 3 1))
(print (pascal 3 2))
(print (pascal 3 3))
(print (pascal 4 0))
(print (pascal 4 1))
(print (pascal 4 2))
(print (pascal 4 3))
(print (pascal 4 4))
(print (pascal 4 5))
(print (pascal 4 10))
