(define (cont-frac n d k)
  (define (iter i result)
    (cond ((< i 1) result)
          ((= i k) (iter (- i 1) (/ (n k) (d k))))
          (else (iter (- i 1) (/ (n k) (+ (d k) result))))))
  (iter k 0)
  )

(print (cont-frac (lambda (i) 1.0)
                  (lambda (i) 1.0)
                  10))
(print (cont-frac (lambda (i) 1.0)
                  (lambda (i) 1.0)
                  11))
